import '../styles/globals.css';

// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';
import MainLayout from '@/components/MainLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
